--- #YAML:1.0
name:               Crashplan-Client
version:            0.001
abstract:           The great new Crashplan::Client!
author:
    - Arnaud (Arhuman) ASSAD <arnaud.assad@jaguar-network.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    JSON:          0
    MIME::Base64:  0
    REST::Client:  0
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
